#' Species Group Data
#'
#' This dataset contains a vector of species groups used in analysis.
#' The groups include categories such as "Waterfowl", "Birds of Prey", and "Shorebirds".
#'
#' @format A character vector with 12 elements:
#' \describe{
#'   \item{COSEWIC}{The conservation status of species.}
#'   \item{Cavity_Birds}{Species that nest in cavities.}
#'   \item{Waterfowl}{Bird species that primarily live on or near water.}
#'   \item{Marine_Birds}{Bird species that live in marine environments.}
#'   \item{Shorebirds}{Bird species typically found along shorelines.}
#'   \item{Wetland_Birds}{Bird species that inhabit wetlands.}
#'   \item{Birds_of_Prey}{Raptors or predatory birds.}
#'   \item{Forest_Birds}{Bird species that live in forested areas.}
#'   \item{Grassland_Birds}{Bird species that inhabit grasslands.}
#'   \item{Aerial_Insectivores}{Birds that feed on insects while flying.}
#'   \item{Arctic_Birds}{Bird species found in Arctic regions.}
#'   \item{Long_Distance_Migrants}{Birds that migrate long distances between breeding and wintering grounds.}
#' }
#'
#' @source The data was derived from internal project datasets and species grouping systems.
#' @keywords datasets
#' @examples
#' data(guild_opt)
#' head(guild_opt)
#'
#' @docType data
"guild_opt"


# ---------------------------------------------------------------------------
# Bootstrap-level relative influence: the source of truth for v5 importance.
# ---------------------------------------------------------------------------

#' Bootstrap-level predictor relative influence (National Models v5)
#'
#' The relative influence of every predictor in every bootstrap replicate of
#' every species x BCR model. This is the source dataset from which
#' \code{bam_predictor_importance_v5} is derived, and from which
#' \code{bam_predictor_importance()} computes its error bars.
#'
#' Relative influence is scaled by \code{gbm::summary.gbm()} to sum to 100 within
#' a single model, i.e. within one species x BCR x bootstrap. Predictors of the
#' same model are therefore negatively correlated by construction, and the
#' variance of a predictor \emph{class} total is not the sum of its predictors'
#' variances. Collapsing to class totals inside each bootstrap -- which requires
#' this dataset rather than the averaged one -- is the only way to put an honest
#' error bar on a class.
#'
#' Averaging \code{rel.inf} over \code{boot} within each species x BCR x predictor
#' reproduces \code{bam_predictor_importance_v5} exactly; a package test asserts
#' this, so the two cannot drift apart.
#'
#' @format A \code{data.frame} with 1,709,760 rows and six columns:
#' \describe{
#'   \item{spp}{Four-letter bird code.}
#'   \item{bcr}{Bird Conservation Region (model subregion).}
#'   \item{boot}{Bootstrap replicate index within that species x BCR model.}
#'   \item{predictor}{Model predictor.}
#'   \item{predictor_class}{Broad class the predictor belongs to.}
#'   \item{rel.inf}{Relative influence of the predictor in that bootstrap. Sums
#'     to 100 within each species x BCR x boot.}
#' }
#' @source Generated by \code{PrepareDataCovariateImportanceV5.R}.
#' @keywords datasets
#' @docType data
"bam_predictor_boot_v5"


# ---------------------------------------------------------------------------
# Species x BCR predictor importance, v5 (derived) and v4 (archived).
# ---------------------------------------------------------------------------

#' Predictor importance per species x BCR (National Models v5)
#'
#' Mean and standard deviation of each predictor's relative influence across the
#' bootstrap replicates of a species x BCR model.
#'
#' This dataset is \emph{derived} from \code{\link{bam_predictor_boot_v5}} by
#' averaging over \code{boot}; a package test asserts the derivation, so the two
#' cannot drift apart. Regenerate both together with
#' \code{PrepareDataCovariateImportanceV5.R}.
#'
#' \code{gbm::summary.gbm()} scales relative influence to sum to 100 within a
#' single model, and averaging over bootstraps preserves that, so
#' \code{mean_rel_inf} sums to exactly 100 within every species x BCR. Values are
#' therefore only interpretable relative to other predictors of the same model,
#' and any summary across models must convert to a within-model share first --
#' summing raw values weights a species by how many BCRs it was modelled in,
#' which ranges from 4 to 33. Unlike \code{\link{bam_predictor_importance_v4}},
#' no filter on relative influence is applied.
#'
#' @format A \code{data.frame} with 53,430 rows and seven columns:
#' \describe{
#'   \item{spp}{Four-letter bird code.}
#'   \item{bcr}{Bird Conservation Region (model subregion).}
#'   \item{predictor}{Model predictor.}
#'   \item{mean_rel_inf}{Mean relative influence across bootstraps. Sums to 100
#'     within each species x BCR.}
#'   \item{sd_rel_inf}{Standard deviation of relative influence across bootstraps.
#'     Predictors within a model are negatively correlated by construction, so
#'     these do not combine by summing variances; use
#'     \code{\link{bam_predictor_boot_v5}} for class-level uncertainty.}
#'   \item{n_boots}{Number of bootstraps in which the predictor had non-zero
#'     relative influence.}
#'   \item{predictor_class}{Broad class the predictor belongs to.}
#' }
#' @source Generated by \code{PrepareDataCovariateImportanceV5.R}.
#' @keywords datasets
#' @docType data
"bam_predictor_importance_v5"


#' Predictor importance per species x BCR (archived National Models v4)
#'
#' The v4 equivalent of \code{\link{bam_predictor_importance_v5}}, retained for
#' comparison with the archived models.
#'
#' \strong{This export is truncated.} Only predictors with a relative influence
#' of at least 1 were retained, leaving a median of two predictors per species x
#' BCR and species x BCR totals ranging from roughly 1 to 88 rather than 100.
#' \code{bam_predictor_barchart()} and \code{bam_predictor_importance()} rescale
#' each species x BCR back to 100 so that models are at least internally
#' consistent, and warn once per session; composition remains biased toward
#' predictor classes made up of few, strongly influential predictors. Treat
#' cross-species and cross-BCR comparison as indicative only. There is no
#' bootstrap-level counterpart for v4, so class error bars fall back to a
#' conservative approximation.
#'
#' @format A \code{data.frame} with 8,912 rows and the same seven columns as
#'   \code{\link{bam_predictor_importance_v5}}.
#' @source Archived Version 4 National Model outputs.
#' @keywords datasets
#' @docType data
"bam_predictor_importance_v4"


# ---------------------------------------------------------------------------
# Bootstrap-level partial dependence: the source of truth for v5 response curves.
# ---------------------------------------------------------------------------

#' Bootstrap-level predictor response curves (National Models v5)
#'
#' The partial dependence of predicted bird density on each model predictor, in
#' every bootstrap replicate of every species x BCR model. This is the dataset
#' from which \code{bam_partial_dependence()} fits its mean response and 95\%
#' confidence ribbon.
#'
#' Curves were generated with \code{gbm::plot.gbm()} at
#' \code{continuous.resolution = 50}. Only species x BCR x predictor combinations
#' in the top 75th percentile of relative influence across all models were
#' retained, so a combination absent from this dataset is not an error: the
#' predictor was simply too weak in that model to be worth plotting. Use
#' \code{\link{bam_predictor_importance_v5}} to find the predictors that matter
#' for a given species x BCR.
#'
#' There is no v4 counterpart; response data for the archived models are not
#' included in the package.
#'
#' @format A \code{tbl_df} with 9,686,705 rows and seven columns:
#' \describe{
#'   \item{species}{Four-letter bird code (70 species).}
#'   \item{bcr}{Bird Conservation Region (model subregion; 33 BCRs).}
#'   \item{var}{Model predictor (89 predictors).}
#'   \item{replicate}{Bootstrap replicate index, 1 to 32, within that
#'     species x BCR model.}
#'   \item{covariate_value}{Value of the predictor at which the response was
#'     evaluated. Stored as \code{character} so that continuous and categorical
#'     predictors can share the column; cast to \code{numeric} when
#'     \code{covariate_type} is \code{"continuous"}.}
#'   \item{covariate_type}{Either \code{"continuous"} or \code{"categorical"}.}
#'   \item{y}{Partial dependence of predicted density on the predictor, in
#'     singing males per hectare.}
#' }
#' @seealso \code{\link{bam_partial_dependence}}
#' @source Generated from the Version 5 National Model objects.
#' @keywords datasets
#' @docType data
"bam_predictor_response_v5"
